FROM python:3.10

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port (Cloud Run uses $PORT)
ENV PORT=8080

# Run Django with Gunicorn
CMD exec gunicorn personalize-food-decision.wsgi:application --bind 0.0.0.0:$PORT